### ISSUE TITLE
can you share 4.10.2391.0 widevinecdm.dll file ?

### ISSUE THREAD

**Issue by joostshao** [yakumo43/WidevineCdm-4.10.2391.0#1]
Thank you first !
can you share 4.10.2391.0 widevinecdm.dll file  (widevinecdm.dll)?

**Comment by yakumo43** [comment]
> Thank you first ! can you share 4.10.2391.0 widevinecdm.dll file (widevinecdm.dll)?

email???

**Comment by yakumo43** [comment]
> > Thank you first ! can you share 4.10.2391.0 widevinecdm.dll file (widevinecdm.dll)?
> 
> email???

**Comment by yakumo43** [comment]
> > Thank you first ! can you share 4.10.2391.0 widevinecdm.dll file (widevinecdm.dll)?
> 
> email???

https://we.tl/t-6y285Cc5tW

**Comment by joostshao** [comment]
> > > Thank you first ! can you share 4.10.2391.0 widevinecdm.dll file (widevinecdm.dll)?
> > 
> > 
> > email???
> 
> https://we.tl/t-6y285Cc5tW

thank you

**Comment by joostshao** [comment]
how to using this in windows pc? 
俺不会用
email： joostshao1989@gmail.com
